### ISSUE TITLE
Bundle without axios?

### ISSUE THREAD

**Issue by quentincaffeino** [prest/prest-node#5]
According to caniuse stats, almost 95% of browsers supports fetch api. Is there any reason why axios must be used with this repo? There could be several builds (with&without axios) or the end user could polyfill fetch with babel for browsers which doesn't support it.

**Comment by guidiego** [comment]
Hey, @quentincaffeino thank you for your contribution! That's only to get a fast kick out :) I will open an issue soon to make something similar to other clients : 

```typescript
PRestAPI.fetcher = fetch | axios | ...anyOne
```

Feel free to open a PR if you want :D

**Comment by quentincaffeino** [comment]
Fetch and Axios APIs are a bit different, how do you see this work internally? What "other clients" do you refer to?

**Comment by guidiego** [comment]
@quentincaffeino for example `swr` from next accept a "fetcher" function. Basically you could write your own fetcher function use any kind of client that you want.
